# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/EE3/Summer/ARMProject/MyBicubic/MyBicubic.srcs/sources_1/ip/float16_mult/float16_mult.xci
# IP: The module: 'float16_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EE3/Summer/ARMProject/MyBicubic/MyBicubic.gen/sources_1/ip/float16_mult/float16_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float16_mult'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/EE3/Summer/ARMProject/MyBicubic/MyBicubic.srcs/sources_1/ip/float16_mult/float16_mult.xci
# IP: The module: 'float16_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EE3/Summer/ARMProject/MyBicubic/MyBicubic.gen/sources_1/ip/float16_mult/float16_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float16_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
